<a href="https://colab.research.google.com/github/fominpskov/pythonProject/blob/master/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Lesson27_ipynb%22%22%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install anvil-uplink

     |████████████████████████████████| 64 kB 2.0 MB/s 
     |████████████████████████████████| 51 kB 177 kB/s 
  Created wheel for ws4py: filename=ws4py-0.5.1-py3-none-any.whl size=45229 sha256=2476fbc9d0150444ce9ffbec8d8496ac6e1c0dfa7792494f36e7260f124c4d72
  Stored in directory: /root/.cache/pip/wheels/29/ea/7d/3410aa0aa0e4402ead9a7a97ab2214804887e0f5c2b76f0c96
Successfully built ws4py


In [ ]:
from keras.models import load_model
from PIL import Image, ImageOps
from keras.preprocessing.image import load_img
import numpy as np
import anvil.server

anvil.server.connect("server_XPVD333GCFFLDNCXECRZXAQ6-WZGOL4CAMJR5DYTL")
import anvil.media
# Load the model
model = load_model('keras_model.h5')
@anvil.server.callable
def predict_pic(pic):
  with anvil.media.TempFile(pic) as f:
    img = load_img(f)
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
  size = (224, 224)
  image = ImageOps.fit(img, size, Image.ANTIALIAS)
  image_array = np.asarray(image)
  normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
  data[0] = normalized_image_array
  prediction = model.predict(data)
  print('Я считаю, что на изображении показан')
  print(prediction)
  mpred = np.argmax(prediction[0])
  print(np.argmax(prediction[0]))
  if mpred == 0:
    text = 'бизон с вероятностью ' + str(prediction[0][0]*100) + ' %'
  elif mpred == 1:
    text = 'слон с вероятностью ' + str(prediction[0][1]*100) + ' %'
  elif mpred == 2:
    text = 'носорог с вероятностью ' +  str(prediction[0][2]*100) + ' %'
  else:
    text = 'зебра с вероятностью ' +  str(prediction[0][3]*100) + ' %'
  
  return text
anvil.server.wait_forever()

Connecting to wss://anvil.works/uplink
Anvil websocket open
Connected to "Default Environment" as SERVER
Я считаю, что на изображении показан
[[2.3533474e-15 1.0000000e+00 1.4542210e-10 1.1792267e-13]]
1
Я считаю, что на изображении показан
[[3.3974914e-08 1.5527105e-08 1.0318198e-08 9.9999988e-01]]
3
Я считаю, что на изображении показан
[[9.9998534e-01 1.4667261e-05 3.5861525e-10 1.6220467e-08]]
0
Я считаю, что на изображении показан
[[3.4021020e-12 1.1775648e-03 5.5964045e-07 9.9882191e-01]]
3
Я считаю, что на изображении показан
[[6.0318240e-07 9.9802846e-01 1.9708565e-03 8.1829214e-08]]
1
Я считаю, что на изображении показан
[[4.3295905e-11 9.9999964e-01 3.1730960e-07 7.1134593e-10]]
1
Я считаю, что на изображении показан
[[1.0999220e-12 8.1125604e-09 1.5836438e-11 1.0000000e+00]]
3
